### ISSUE TITLE
Roadmap for v1.3

### ISSUE THREAD

**Issue by lukaslangrock** [lukaslangrock/ShutdownTimerClassic#19]
This issue outlines which (non-trivial) features/fixes/changes have been selected or are considered for future versions of the application.

# Known issues in 1.2.3

- Crashing at start (#30)
Not enough data to pinpoint the exact source of the issue, but it seems like not many people are affected. 

# Version 1.3.0
- [x] Fix for known issue #30
- [x] Select a time of day for countdown (#11)
- [x] Transparent countdown window (part of #16)
- [x] Pause/resume countdown (part of #16)
- [x] Update remaining time while active (part of #16)
- [x] Custom action (command) instead of power actions (part of #18)
- [x] Option to disable confirmation dialogues (#33)
- [x] Disallow multiple instances by default (but configurable in settings) (#27, #44, thanks to @MatheusOliveira-dev)

## Version 1.3.1 - The "Custom" Update
- [ ] Custom buttons for adding more time to the countdown (#16 and #17)
- [ ] Custom events during countdown (part of #16 and #17)
- [ ] Custom Hotkey support (#16)
- [ ] Customizable notification messages (#41)
- [ ] Ability for timer reset on mouse movement (part of #18)

## Features under consideration

- [ ] Scheduling shutdowns (#8 and #9)

**Comment by lukaslangrock** [comment]
The changes scheduled for later versions will be handled in a new issue. Also, sorry for my absence from this project, this release - especially the bugfix - has been staging for quite a while now, hopefully there will be no big issues with this release.

**Comment by lukaslangrock** [comment]
Due to some (partially new) bugs existing in `1.3.0`, I'll postpone the features planned for `1.3.1` to `1.3.2` and focus on fixing the bugs in`1.3.1` and publish this as fast as possible, notable #49, #48, and #46
